apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "bob" to read pods in the "engineering" namespace.
kind: RoleBinding
metadata:
  name: read-pods
  namespace: engineering 
subjects:
- kind: User
  name: bob # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pod-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
